#!/bin/bash

set -e

IMAGE=dpretty

if [ -d "$1" ]; then
    USER_DIR="$(cd "$1"; pwd)"
else
    USER_DIR="$(pwd)"
fi

SELINUXOPT=""
[ -x "$(which getenforce)" ] && [ "$(getenforce)" = "Enforcing" ] && SELINUXOPT=":z"
ENGINE_OPTS=("-v" "${USER_DIR}:/user_dir${SELINUXOPT}" "-i")

tty &>/dev/null && ENGINE_OPTS+=('-t')

SCRIPTDIR="$(dirname "$(readlink -fn "$0")")"
cd "$SCRIPTDIR"
PATH=".:$PATH"

if [ -x "$(command -v podman)" ]; then
    ENGINE=podman
elif [ -x "$(command -v docker)" ]; then
    ENGINE=docker
    ENGINE_OPTS+=("-u" "$(id -u):$(id -g)")
else
    echo "Podman (recommended) or docker must be installed"
fi

if ! hide-short-output $ENGINE build . -t $IMAGE; then
    echo "'$ENGINE build -t .' failed"
    exit 1
fi

"$ENGINE" run "${ENGINE_OPTS[@]}" "$IMAGE" dpretty.sh "$@"
