#!/bin/bash

set -e

IMAGE=dpretty

INPUT_SRC="$(pwd)"

SKIP_BUILD=''
COMMAND=dpretty.sh

EXTRA_ARGS=()

while getopts :nr:g:e: OPT; do
    case $OPT in
        n)
            SKIP_BUILD=true
            ;;
        r)
            EXTRA_ARGS+=(-r "$OPTARG")
            ;;
        g)
            EXTRA_ARGS+=(-g "$OPTARG")
            ;;
        e)
            COMMAND="$OPTARG"
            ;;
        *)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

SELINUXOPT=""
[ -x "$(which getenforce)" ] && [ "$(getenforce)" = "Enforcing" ] && SELINUXOPT=":z"
ENGINE_OPTS=("--rm" "-v" "${INPUT_SRC}:/input_src${SELINUXOPT}" "-i")

tty &> /dev/null && ENGINE_OPTS+=('-t')

SCRIPTDIR="$(dirname "$(readlink -fn "$0")")"
cd "$SCRIPTDIR"
PATH=".:$PATH"

if [ -x "$(command -v podman)" ]; then
    ENGINE=podman
elif [ -x "$(command -v docker)" ]; then
    ENGINE=docker
    ENGINE_OPTS+=("-u" "$(id -u):$(id -g)")
else
    echo "Podman (recommended) or docker must be installed"
fi

if [ -z "$SKIP_BUILD" ]; then
    if ! hide-short-output -t 4 $ENGINE build . -t $IMAGE; then
        echo "'$ENGINE build -t .' failed"
        exit 1
    fi
fi

"$ENGINE" run "${ENGINE_OPTS[@]}" "$IMAGE" "$COMMAND" "${EXTRA_ARGS[@]}" "$@"
