#!/bin/bash

set -e

IMAGE=dpretty

INPUT_SRC="$(pwd)"

SELINUXOPT=""
[ -x "$(which getenforce)" ] && [ "$(getenforce)" = "Enforcing" ] && SELINUXOPT=":z"
ENGINE_OPTS=("--rm" "-v" "${INPUT_SRC}:/input_src${SELINUXOPT}" "-i")

tty &>/dev/null && ENGINE_OPTS+=('-t')

SCRIPTDIR="$(dirname "$(readlink -fn "$0")")"
cd "$SCRIPTDIR"
PATH=".:$PATH"

if [ -x "$(command -v podman)" ]; then
    ENGINE=podman
elif [ -x "$(command -v docker)" ]; then
    ENGINE=docker
    ENGINE_OPTS+=("-u" "$(id -u):$(id -g)")
else
    echo "Podman (recommended) or docker must be installed"
fi

if ! hide-short-output -t 4 $ENGINE build . -t $IMAGE; then
    echo "'$ENGINE build -t .' failed"
    exit 1
fi

"$ENGINE" run "${ENGINE_OPTS[@]}" "$IMAGE" dpretty.sh "$@"
