#!/bin/bash

# git-rapply -- Apply a command across a range of git commits
#
# git-rapply will execute a given command on the files modified by a
# range of git commits -- by default, all commits in your branch since
# your tracking branch ("@{upstream}")
#
# The script will create one initial commit that applies the given
# command to all the files your commit range modifies, followed by
# recreated versions of each commit in the range, but with the command
# applied.

# Exit if anything goes wrong -- see below for error handler that
# recovers the state.
set -e

# Record the last commit we want to make sure is represented in our
# history.
END="$(git log -1 --pretty=%H)"

COMMAND=$1
shift

if ! [ -x "$(command -v "$COMMAND")" ]; then
    echo "$COMMAND does not appear to be available -- install it before proceeding"
    exit 1
fi

# Terminate early if there's any changes still to be commited -- those
# changes are likely to be lost if we're re-writing git commit
# history.

# Checks if git is clean or has uncommitted changes
git_is_clean() {
    if [ -n "$(git status --untracked-files=no --porcelain)" ]; then
        return 1
    fi
    return 0
}

if ! git_is_clean; then
    echo "Git tree is unclean -- commit or stash your changes before proceeding"
    exit 2
fi

# In the event of a failure (either associated with the 'set -e'
# setting above, or due to the script being terminated by Ctrl-C or
# similar, restore the repository to the state we started in.
recover() {
    echo "Something bad happened! Resetting back to $END"
    git reset --hard "$END"
}
trap "recover" SIGINT SIGTERM ERR

# By default, operate on the commits produced since we diverged from
# the tracking branch, but allow a different starting commit or range.
RANGE="@{upstream}..$END"

if [ -n "$1" ]; then
    if echo "$1" | grep -E '[.][.].' &>/dev/null ; then
        echo "Full range provided: \"$1\""
        RANGE="$1"
    elif echo "$1" | grep -E '[.][.]' &>/dev/null ; then
        echo "Partial range provided"
        RANGE="${1}${END}"
    else
        echo "Starting point provided"
        RANGE="$1..$END"
    fi
fi

if [ -n "$(git log --merges "$RANGE")" ]; then
    echo "Git range $RANGE includes merge commits, and therefore can't be automatically iterated over"
    exit 1
fi

# Record the set of all files modified in this git range (including
# files the filter changes and then changes back).
get_touched_files() {
    git log --pretty=%H "$RANGE" | while read -r SHA; do
        git diff-tree --no-commit-id --name-only -r "$SHA"
    done | sort | uniq
}
FILES="$(get_touched_files)"

# Move our git repository to just before the selected range.
START="${RANGE/%..*}"
START="$(git log -1 --pretty=%H "$START")"

mapfile -t COMMITS < <(git log --topo-order --reverse --pretty=%H "$RANGE")
WORKTREE="$(mktemp -d)"
git worktree add "$WORKTREE"
pushd "$WORKTREE"
TMPBRANCH=$(git rev-parse --abbrev-ref HEAD)

git reset --hard "$START" > /dev/null


# Appyly command to each modified file (if it exists)
filterfiles() {
    local SHA=$1
    echo "$FILES" | while IFS='' read -r FILE; do
        if [ -e "$FILE" ]; then
            if [ -n "$SHA" ] && [ -z "$(git show "$SHA" "$FILE")" ]; then
                # Not modified, no point filtering it
                git checkout "$FILE" &> /dev/null
                continue
            fi
            echo "Filtering \"$FILE\""
            "$COMMAND" "$FILE"
        fi
    done
}

# Apply command to all modified files initially, so the subsequent
# commits are simpler and cleaner
echo "Performing initial filter operation"
filterfiles
git add -A -f .
git commit -F- <<EOCOMMITMESSAGE || true
Auto-applying changes on below files, to make subsequent commits easier to read:

$FILES
EOCOMMITMESSAGE

# Utility to reset the working tree contents to a selected sha, while
# keeping the git repository pointed at the same commit. Done by a
# hard-reset (to get the correct content) followed by a normal reset
# (which restores the index/HEAD)
reset_working_tree() {
    local SHA=$1
    HEAD="$(git log -1 --pretty=%H)"
    git reset --hard "$SHA" > /dev/null
    git reset "$HEAD" > /dev/null
}

# Iterate over all the commits in our range, in the order they are in
# the commit tree
for SHA in "${COMMITS[@]}"; do
    echo "Recreating $SHA without output"

    # Restore the content that was in this commit
    reset_working_tree "$SHA"

    # Apply command to all modified files. This restores the work done
    # in the preceeding git history, as well as the work produced in
    # the current SHA, leaving the git differences as just the new
    # work in the current SHA, with the cleanup applied
    filterfiles "$SHA"

    # Create a new git commit with the metadata from the commit we're re-creating.
    git add -f -A .
    git commit -C"$SHA" > /dev/null || true
done

# At this point, we're finished. We can now as a sanity check verify
# that we have all the content we started with, and flag a warning if
# there is any missing content.

reset_working_tree "$END"
filterfiles

DONESHA="$(git log -1 --pretty=%H)"

cleanup_worktree() {
    git worktree remove --force "$WORKTREE"
    git branch -D "$TMPBRANCH"
}

if ! git_is_clean; then
    git add -f -A .
    git commit -m "Missing changes"
    MISSINGSHA="$(git log -1 --pretty=%H)"
    echo "Error: modified files are still present in the repository. This should not happen. Consider filing a bug."
    echo
    echo "You can either adopt the filtered files without those extra changes  by running:"
    echo
    echo "  git reset --hard $DONESHA"
    echo
    echo "Or, adopt the filtered files *WITH* the extra changes, by running:"
    echo
    echo "  git reset --hard $MISSINGSHA"
    echo
    cleanup_worktree
else
    popd
    git reset --hard "$DONESHA"
    cleanup_worktree
    echo "Finished successfully"
fi
