#!/bin/bash

set -e
TIMEOUT=2
FLAGFILE=$(mktemp -p /tmp hso-flagfile-XXXX)
OUTFILE=$(mktemp -p /tmp hso-outfile-XXXX)
RCFILE=$(mktemp -p /tmp hso-rcfile-XXXX)

cleanup() {
    rm -f "$FLAGFILE"
    rm -f "$OUTFILE"
    rm -f "$RCFILE"
}
trap cleanup SIGINT SIGTERM EXIT

while getopts :t: OPT; do
    case $OPT in
        t)
            TIMEOUT="$OPTARG"
            ;;
        *)
            echo "Invalid option: -$OPTARG"
            exit 1
            ;;
    esac
done
shift $(expr $OPTIND - 1 )

monitor_for_exit() {
    local FLAGFILE="$1"; shift
    local OUTFILE="$1"; shift

    if "$@" &> "$OUTFILE"; then
        echo "0" > "$RCFILE"
    else
        echo "$?" > "$RCFILE"
    fi
    rm -f "$FLAGFILE"
}

monitor_for_exit "$FLAGFILE" "$OUTFILE" "$@" &

ENDTIME=$[$(date +%s) + $TIMEOUT]
while [ -e $FLAGFILE -a $(date +%s) -lt $ENDTIME ]; do
    sleep 0.25
done

RC=$(cat "$RCFILE")

if [ -e "$FLAGFILE" ] || [ "$RC" -ne 0 ]; then
    tail -n +1 -f "$OUTFILE" &
    while [ -e "$FLAGFILE" ]; do sleep 0.25; done
fi

rm -f "$OUTFILE"
